sigo teniendo problemas en api/generate-plan me da este error, "err": {                     "name": "TypeError",                     "source": "server",                     "message": "GenerateInitialPlanOutputSchema.openapi is not a function",                     "stack": "TypeError: GenerateInitialPlanOutputSchema.openapi is not a function\n    at [project]/src/ai/flows/generate-initial-plan.ts [app-route] (ecmascript) (/home/user/studio/.next/server/chunks/[root of the server]__a1b20492._.js:390:50)\n    at instantiateModule (/home/user/studio/.next/server/chunks/[turbopack]_runtime.js:593:23)\n    at getOrInstantiateModuleFromParent (/home/user/studio/.next/server/chunks/[turbopack]_runtime.js:652:12)\n    at esmImport (/home/user/studio/.next/server/chunks/[turbopack]_runtime.js:132:20)\n    at [project]/src/app/api/generate-plan/route.ts [app-route] (ecmascript) (/home/user/studio/.next/server/chunks/[root of the server]__a1b20492._.js:742:181)\n    at instantiateModule (/home/user/studio/.next/server/chunks/[turbopack]_runtime.js:593:23)\n    at getOrInstantiateModuleFromParent (/home/user/studio/.next/server/chunks/[turbopack]_runtime.js:652:12)\n    at esmImport (/home/user/studio/.next/server/chunks/[turbopack]_runtime.js:132:20)\n    at [project]/node_modules/next/dist/esm/build/templates/app-route.js { INNER_APP_ROUTE =\u003e \"[project]/src/app/api/generate-plan/route.ts [app-route] (ecmascript)\" } [app-route] (ecmascript) (/home/user/studio/.next/server/chunks/node_modules_next_26f15291._.js:15059:174)\n    at instantiateModule (/home/user/studio/.next/server/chunks/[turbopack]_runtime.js:593:23)\n    at instantiateRuntimeModule (/home/user/studio/.next/server/chunks/[turbopack]_runtime.js:660:12)\n    at Object.getOrInstantiateRuntimeModule (/home/user/studio/.next/server/chunks/[turbopack]_runtime.js:676:12)\n    at Object.\u003canonymous\u003e (/home/user/studio/.next/server/app/api/generate-plan/route.js:23:9)\n    at Module._compile (node:internal/modules/cjs/loader:1529:14)\n    at Module._extensions..js (node:internal/modules/cjs/loader:1613:10)\n    at Module.load (node:internal/modules/cjs/loader:1275:32)\n    at Module._load (node:internal/modules/cjs/loader:1096:12)\n    at Module.require (node:internal/modules/cjs/loader:1298:19)\n    at mod.require (/home/user/studio/node_modules/next/dist/server/require-hook.js:65:28)\n    at require (node:internal/modules/helpers:182:18)\n    at requirePage (/home/user/studio/node_modules/next/dist/server/require.js:103:84)\n    at loadComponentsImpl (/home/user/studio/node_modules/next/dist/server/load-components.js:129:57)\n    at async DevServer.findPageComponentsImpl (/home/user/studio/node_modules/next/dist/server/next-server.js:808:36)\n    at async DevServer.findPageComponents (/home/user/studio/node_modules/next/dist/server/dev/next-dev-server.js:628:16)\n    at async DevServer.renderPageComponent (/home/user/studio/node_modules/next/dist/server/base-server.js:2379:24)\n    at async DevServer.renderToResponseImpl (/home/user/studio/node_modules/next/dist/server/base-server.js:2430:32)\n    at async DevServer.pipeImpl (/home/user/studio/node_modules/next/dist/server/base-server.js:1003:25)\n    at async NextNodeServer.handleCatchallRenderRequest (/home/user/studio/node_modules/next/dist/server/next-server.js:304:17)\n    at async DevServer.handleRequestImpl (/home/user/studio/node_modules/next/dist/server/base-server.js:895:17)\n    at async /home/user/studio/node_modules/next/dist/server/dev/next-dev-server.js:371:20\n    at async Span.traceAsyncFn (/home/user/studio/node_modules/next/dist/trace/trace.js:157:20)\n    at async DevServer.handleRequest (/home/user/studio/node_modules/next/dist/server/dev/next-dev-server.js:368:24)\n    at async invokeRender (/home/user/studio/node_modules/next/dist/server/lib/router-server.js:247:21)\n    at async handleRequest (/home/user/studio/node_modules/next/dist/server/lib/router-server.js:438:24)\n    at async requestHandlerImpl (/home/user/studio/node_modules/next/dist/server/lib/router-server.js:462:13)\n    at async Server.requestListener (/home/user/studio/node_modules/next/dist/server/lib/start-server.js:158:13)"                 },